// Mocks generated by Mockito 5.4.4 from annotations
// in trip_planner/test/features/day_trips/data/repositories/day_trips_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter/material.dart' as _i5;
import 'package:flutter_polyline_points/flutter_polyline_points.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:trip_planner/features/day_trips/data/datasources/day_trips_data_source.dart' as _i2;
import 'package:trip_planner/features/day_trips/domain/entities/day_trip.dart' as _i4;
import 'package:trip_planner/features/day_trips/domain/entities/trip_stops_directions.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DayTripsDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDayTripsDataSource extends _i1.Mock implements _i2.DayTripsDataSource {
  @override
  _i3.Future<void> addDayTrip({
    required String? tripId,
    required _i4.DayTrip? dayTrip,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addDayTrip,
          [],
          {
            #tripId: tripId,
            #dayTrip: dayTrip,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.DayTrip>> listenDayTrips(String? tripId) => (super.noSuchMethod(
        Invocation.method(
          #listenDayTrips,
          [tripId],
        ),
        returnValue: _i3.Stream<List<_i4.DayTrip>>.empty(),
        returnValueForMissingStub: _i3.Stream<List<_i4.DayTrip>>.empty(),
      ) as _i3.Stream<List<_i4.DayTrip>>);

  @override
  _i3.Future<void> updateDayTripsIndexes({
    required String? tripId,
    required List<_i4.DayTrip>? dayTrips,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDayTripsIndexes,
          [],
          {
            #tripId: tripId,
            #dayTrips: dayTrips,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateDayTrip({
    required String? id,
    required String? tripId,
    required String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDayTrip,
          [],
          {
            #id: id,
            #tripId: tripId,
            #description: description,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateDayTripStartTime({
    required String? id,
    required String? tripId,
    required _i5.TimeOfDay? startTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDayTripStartTime,
          [],
          {
            #id: id,
            #tripId: tripId,
            #startTime: startTime,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteDayTrip({
    required String? tripId,
    required String? dayTripId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDayTrip,
          [],
          {
            #tripId: tripId,
            #dayTripId: dayTripId,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveTripStopsDirections({
    required String? tripId,
    required String? dayTripId,
    required List<_i6.TripStopsDirections>? tripStopsDirections,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTripStopsDirections,
          [],
          {
            #tripId: tripId,
            #dayTripId: dayTripId,
            #tripStopsDirections: tripStopsDirections,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<_i4.DayTrip> listenDayTrip(
    String? tripId,
    String? dayTripId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #listenDayTrip,
          [
            tripId,
            dayTripId,
          ],
        ),
        returnValue: _i3.Stream<_i4.DayTrip>.empty(),
        returnValueForMissingStub: _i3.Stream<_i4.DayTrip>.empty(),
      ) as _i3.Stream<_i4.DayTrip>);

  @override
  dynamic updateTripStopsDirectionsUpToDate({
    required String? tripId,
    required String? dayTripId,
    required bool? isUpToDate,
    _i7.TravelMode? travelMode,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateTripStopsDirectionsUpToDate,
          [],
          {
            #tripId: tripId,
            #dayTripId: dayTripId,
            #isUpToDate: isUpToDate,
            #travelMode: travelMode,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  dynamic updateDayTripShowDirections({
    required String? tripId,
    required String? dayTripId,
    required bool? showDirections,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateDayTripShowDirections,
          [],
          {
            #tripId: tripId,
            #dayTripId: dayTripId,
            #showDirections: showDirections,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  dynamic updateDayTripUseDifferentDirectionsColors({
    required String? tripId,
    required String? dayTripId,
    required bool? useDifferentDirectionsColors,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateDayTripUseDifferentDirectionsColors,
          [],
          {
            #tripId: tripId,
            #dayTripId: dayTripId,
            #useDifferentDirectionsColors: useDifferentDirectionsColors,
          },
        ),
        returnValueForMissingStub: null,
      );
}
