// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWG1chQTWea3i1AeaQBk3nFlyZDI_jwRQ',
    appId: '1:178262421662:web:659e43ecb42bccc5e10b8f',
    messagingSenderId: '178262421662',
    projectId: 'trip-planner-11ffe',
    authDomain: 'trip-planner-11ffe.firebaseapp.com',
    databaseURL: 'https://trip-planner-11ffe.firebaseio.com',
    storageBucket: 'trip-planner-11ffe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwWfCJktwEdd4nNZGDO7mm6nwgYNVAX5I',
    appId: '1:178262421662:android:4c70dd3491bfbfbb',
    messagingSenderId: '178262421662',
    projectId: 'trip-planner-11ffe',
    databaseURL: 'https://trip-planner-11ffe.firebaseio.com',
    storageBucket: 'trip-planner-11ffe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn1995xM3OjXMhfjEeIpoLGwIHQQayErU',
    appId: '1:178262421662:ios:4df4f49599c08d9ce10b8f',
    messagingSenderId: '178262421662',
    projectId: 'trip-planner-11ffe',
    databaseURL: 'https://trip-planner-11ffe.firebaseio.com',
    storageBucket: 'trip-planner-11ffe.appspot.com',
    androidClientId: '178262421662-2o4eo75uk6fbfqqiu6m270vo348c1r6g.apps.googleusercontent.com',
    iosClientId: '178262421662-lru3hb1iq3voilf01f8ris25b17hkqfn.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn1995xM3OjXMhfjEeIpoLGwIHQQayErU',
    appId: '1:178262421662:ios:bd2e5bd34973e8e3e10b8f',
    messagingSenderId: '178262421662',
    projectId: 'trip-planner-11ffe',
    databaseURL: 'https://trip-planner-11ffe.firebaseio.com',
    storageBucket: 'trip-planner-11ffe.appspot.com',
    androidClientId: '178262421662-2o4eo75uk6fbfqqiu6m270vo348c1r6g.apps.googleusercontent.com',
    iosClientId: '178262421662-41i61rvacmtpn0ta1j0ipfmif7p7npod.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripPlanner.RunnerTests',
  );
}
