// Mocks generated by Mockito 5.4.4 from annotations
// in trip_planner/test/features/import_old_trips/presentation/cubit/import_old_trips_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:trip_planner/features/import_old_trips/domain/entities/old_trip.dart'
    as _i6;
import 'package:trip_planner/features/import_old_trips/domain/usecases/import_old_trip.dart'
    as _i7;
import 'package:trip_planner/features/import_old_trips/domain/usecases/read_old_trips.dart'
    as _i3;
import 'package:trip_planner/features/import_old_trips/errors/import_old_trips_failure.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ReadOldTrips].
///
/// See the documentation for Mockito's code generation for more information.
class MockReadOldTrips extends _i1.Mock implements _i3.ReadOldTrips {
  @override
  _i4.Future<_i2.Either<_i5.ImportOldTripsFailure, List<_i6.OldTrip>>> call(
          _i3.ReadOldTripsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.ImportOldTripsFailure, List<_i6.OldTrip>>>.value(
            _FakeEither_0<_i5.ImportOldTripsFailure, List<_i6.OldTrip>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub: _i4.Future<
                _i2.Either<_i5.ImportOldTripsFailure, List<_i6.OldTrip>>>.value(
            _FakeEither_0<_i5.ImportOldTripsFailure, List<_i6.OldTrip>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4
          .Future<_i2.Either<_i5.ImportOldTripsFailure, List<_i6.OldTrip>>>);
}

/// A class which mocks [ImportOldTrips].
///
/// See the documentation for Mockito's code generation for more information.
class MockImportOldTrips extends _i1.Mock implements _i7.ImportOldTrips {
  @override
  _i4.Future<_i2.Either<_i5.ImportOldTripsFailure, void>> call(
          _i7.ImportOldTripsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.ImportOldTripsFailure, void>>.value(
                _FakeEither_0<_i5.ImportOldTripsFailure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.ImportOldTripsFailure, void>>.value(
                _FakeEither_0<_i5.ImportOldTripsFailure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.ImportOldTripsFailure, void>>);
}
