import 'package:auto_route/auto_route.dart';
import 'package:injectable/injectable.dart';

import 'app_router.gr.dart'; // this is the file that is generated by the router generation process

@singleton
@AutoRouterConfig()
class AppRouter extends $AppRouter {
  @override
  RouteType get defaultRouteType =>
      const RouteType.custom(transitionsBuilder: TransitionsBuilders.slideRightWithFade);

  @override
  List<AutoRoute> get routes => [
        AutoRoute(page: HomeRoute.page, initial: true),
        AutoRoute(page: LoginSignupRoute.page),
        AutoRoute(page: TripsRoute.page),
        AutoRoute(page: NewTripRoute.page),
        AutoRoute(page: TripRoute.page),
        AutoRoute(page: NewDayTripRoute.page),
        AutoRoute(page: DayTripRoute.page),
        AutoRoute(page: NewTripStopRoute.page),
        AutoRoute(page: TripStopRoute.page),
        AutoRoute(page: AccountRoute.page),
        AutoRoute(page: ImportOldTripsRoute.page),
        AutoRoute(page: InfoContactsRoute.page),
        AutoRoute(page: SettingsRoute.page),
        AutoRoute(page: DiscoverNewTripsRoute.page),
        AutoRoute(page: DiscoverNewDailyTripsRoute.page),
        AutoRoute(page: DiscoverNewTripStopsRoute.page),
        AutoRoute(page: DiscoverNewTripStopRoute.page),
        AutoRoute(page: TutorialRoute.page),
      ];
}
