// Mocks generated by Mockito 5.4.4 from annotations
// in trip_planner/test/features/day_trips/presentation/cubit/trip_stops_map_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:dartz/dartz.dart' as _i3;
import 'package:firebase_core/firebase_core.dart' as _i5;
import 'package:firebase_crashlytics/firebase_crashlytics.dart' as _i14;
import 'package:flutter/material.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:trip_planner/features/day_trips/domain/entities/day_trip.dart'
    as _i13;
import 'package:trip_planner/features/day_trips/domain/entities/trip_stops_directions.dart'
    as _i9;
import 'package:trip_planner/features/day_trips/domain/repositories/day_trips_repository.dart'
    as _i4;
import 'package:trip_planner/features/day_trips/domain/usecases/listen_day_trip.dart'
    as _i12;
import 'package:trip_planner/features/day_trips/domain/usecases/save_trip_stops_directions.dart'
    as _i10;
import 'package:trip_planner/features/day_trips/domain/usecases/update_day_trip_show_directions.dart'
    as _i17;
import 'package:trip_planner/features/day_trips/domain/usecases/update_day_trip_use_different_directions_colors.dart'
    as _i18;
import 'package:trip_planner/features/day_trips/domain/usecases/update_trip_stops_directions_up_to_date.dart'
    as _i16;
import 'package:trip_planner/features/day_trips/errors/day_trips_failure.dart'
    as _i11;
import 'package:trip_planner/features/google_places/domain/repositories/google_places_repository.dart'
    as _i2;
import 'package:trip_planner/features/google_places/domain/usecases/fetch_polyline_points.dart'
    as _i6;
import 'package:trip_planner/features/google_places/errors/google_places_failure.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGooglePlacesRepository_0 extends _i1.SmartFake
    implements _i2.GooglePlacesRepository {
  _FakeGooglePlacesRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDayTripsRepository_2 extends _i1.SmartFake
    implements _i4.DayTripsRepository {
  _FakeDayTripsRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseApp_3 extends _i1.SmartFake implements _i5.FirebaseApp {
  _FakeFirebaseApp_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FetchTripStopsDirections].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchTripStopsDirections extends _i1.Mock
    implements _i6.FetchTripStopsDirections {
  @override
  _i2.GooglePlacesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeGooglePlacesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeGooglePlacesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.GooglePlacesRepository);

  @override
  _i7.Future<_i3.Either<_i8.GooglePlacesFailure, List<_i9.TripStopsDirections>>>
      call(_i6.FetchTripStopsDirectionsParams? params) => (super.noSuchMethod(
            Invocation.method(
              #call,
              [params],
            ),
            returnValue: _i7.Future<
                _i3.Either<_i8.GooglePlacesFailure,
                    List<_i9.TripStopsDirections>>>.value(_FakeEither_1<
                _i8.GooglePlacesFailure, List<_i9.TripStopsDirections>>(
              this,
              Invocation.method(
                #call,
                [params],
              ),
            )),
            returnValueForMissingStub: _i7.Future<
                _i3.Either<_i8.GooglePlacesFailure,
                    List<_i9.TripStopsDirections>>>.value(_FakeEither_1<
                _i8.GooglePlacesFailure, List<_i9.TripStopsDirections>>(
              this,
              Invocation.method(
                #call,
                [params],
              ),
            )),
          ) as _i7.Future<
              _i3
              .Either<_i8.GooglePlacesFailure, List<_i9.TripStopsDirections>>>);
}

/// A class which mocks [SaveTripStopsDirections].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveTripStopsDirections extends _i1.Mock
    implements _i10.SaveTripStopsDirections {
  @override
  _i4.DayTripsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeDayTripsRepository_2(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeDayTripsRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.DayTripsRepository);

  @override
  _i7.Future<_i3.Either<_i11.DayTripsFailure, void>> call(
          _i10.SaveTripStopsDirectionsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i7.Future<_i3.Either<_i11.DayTripsFailure, void>>.value(
            _FakeEither_1<_i11.DayTripsFailure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i3.Either<_i11.DayTripsFailure, void>>.value(
                _FakeEither_1<_i11.DayTripsFailure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i7.Future<_i3.Either<_i11.DayTripsFailure, void>>);
}

/// A class which mocks [ListenDayTrip].
///
/// See the documentation for Mockito's code generation for more information.
class MockListenDayTrip extends _i1.Mock implements _i12.ListenDayTrip {
  @override
  _i4.DayTripsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeDayTripsRepository_2(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeDayTripsRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.DayTripsRepository);

  @override
  _i7.Stream<_i3.Either<_i11.DayTripsFailure, _i13.DayTrip>> call(
          _i12.ListenDayTripParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i7.Stream<_i3.Either<_i11.DayTripsFailure, _i13.DayTrip>>.empty(),
        returnValueForMissingStub:
            _i7.Stream<_i3.Either<_i11.DayTripsFailure, _i13.DayTrip>>.empty(),
      ) as _i7.Stream<_i3.Either<_i11.DayTripsFailure, _i13.DayTrip>>);
}

/// A class which mocks [FirebaseCrashlytics].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseCrashlytics extends _i1.Mock
    implements _i14.FirebaseCrashlytics {
  @override
  _i5.FirebaseApp get app => (super.noSuchMethod(
        Invocation.getter(#app),
        returnValue: _FakeFirebaseApp_3(
          this,
          Invocation.getter(#app),
        ),
        returnValueForMissingStub: _FakeFirebaseApp_3(
          this,
          Invocation.getter(#app),
        ),
      ) as _i5.FirebaseApp);

  @override
  set app(_i5.FirebaseApp? _app) => super.noSuchMethod(
        Invocation.setter(
          #app,
          _app,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isCrashlyticsCollectionEnabled => (super.noSuchMethod(
        Invocation.getter(#isCrashlyticsCollectionEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  Map<dynamic, dynamic> get pluginConstants => (super.noSuchMethod(
        Invocation.getter(#pluginConstants),
        returnValue: <dynamic, dynamic>{},
        returnValueForMissingStub: <dynamic, dynamic>{},
      ) as Map<dynamic, dynamic>);

  @override
  _i7.Future<bool> checkForUnsentReports() => (super.noSuchMethod(
        Invocation.method(
          #checkForUnsentReports,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  void crash() => super.noSuchMethod(
        Invocation.method(
          #crash,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> deleteUnsentReports() => (super.noSuchMethod(
        Invocation.method(
          #deleteUnsentReports,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> didCrashOnPreviousExecution() => (super.noSuchMethod(
        Invocation.method(
          #didCrashOnPreviousExecution,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> recordError(
    dynamic exception,
    StackTrace? stack, {
    dynamic reason,
    Iterable<Object>? information = const [],
    bool? printDetails,
    bool? fatal = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordError,
          [
            exception,
            stack,
          ],
          {
            #reason: reason,
            #information: information,
            #printDetails: printDetails,
            #fatal: fatal,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> recordFlutterError(
    _i15.FlutterErrorDetails? flutterErrorDetails, {
    bool? fatal = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordFlutterError,
          [flutterErrorDetails],
          {#fatal: fatal},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> recordFlutterFatalError(
          _i15.FlutterErrorDetails? flutterErrorDetails) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordFlutterFatalError,
          [flutterErrorDetails],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> log(String? message) => (super.noSuchMethod(
        Invocation.method(
          #log,
          [message],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> sendUnsentReports() => (super.noSuchMethod(
        Invocation.method(
          #sendUnsentReports,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setCrashlyticsCollectionEnabled(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCrashlyticsCollectionEnabled,
          [enabled],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setUserIdentifier(String? identifier) => (super.noSuchMethod(
        Invocation.method(
          #setUserIdentifier,
          [identifier],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setCustomKey(
    String? key,
    Object? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCustomKey,
          [
            key,
            value,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [UpdateTripStopsDirectionsUpToDate].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateTripStopsDirectionsUpToDate extends _i1.Mock
    implements _i16.UpdateTripStopsDirectionsUpToDate {
  @override
  _i4.DayTripsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeDayTripsRepository_2(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeDayTripsRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.DayTripsRepository);

  @override
  _i7.Future<_i3.Either<_i11.DayTripsFailure, void>> call(
          _i16.UpdateTripStopsDirectionsUpToDateParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i7.Future<_i3.Either<_i11.DayTripsFailure, void>>.value(
            _FakeEither_1<_i11.DayTripsFailure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i3.Either<_i11.DayTripsFailure, void>>.value(
                _FakeEither_1<_i11.DayTripsFailure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i7.Future<_i3.Either<_i11.DayTripsFailure, void>>);
}

/// A class which mocks [UpdateDayTripShowDirections].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateDayTripShowDirections extends _i1.Mock
    implements _i17.UpdateDayTripShowDirections {
  @override
  _i4.DayTripsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeDayTripsRepository_2(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeDayTripsRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.DayTripsRepository);

  @override
  _i7.Future<_i3.Either<_i11.DayTripsFailure, void>> call(
          _i17.UpdateDayTripShowDirectionsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i7.Future<_i3.Either<_i11.DayTripsFailure, void>>.value(
            _FakeEither_1<_i11.DayTripsFailure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i3.Either<_i11.DayTripsFailure, void>>.value(
                _FakeEither_1<_i11.DayTripsFailure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i7.Future<_i3.Either<_i11.DayTripsFailure, void>>);
}

/// A class which mocks [UpdateDayTripUseDifferentDirectionsColors].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateDayTripUseDifferentDirectionsColors extends _i1.Mock
    implements _i18.UpdateDayTripUseDifferentDirectionsColors {
  @override
  _i4.DayTripsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeDayTripsRepository_2(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeDayTripsRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.DayTripsRepository);

  @override
  _i7.Future<_i3.Either<_i11.DayTripsFailure, void>> call(
          _i18.UpdateDayTripUseDifferentDirectionsColorsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i7.Future<_i3.Either<_i11.DayTripsFailure, void>>.value(
            _FakeEither_1<_i11.DayTripsFailure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i3.Either<_i11.DayTripsFailure, void>>.value(
                _FakeEither_1<_i11.DayTripsFailure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i7.Future<_i3.Either<_i11.DayTripsFailure, void>>);
}
